version: '3'

services:
  nginx:
    container_name: myprac_nginx
    build:
      context: ./docker/dev/nginx/
    ports:
      - 80:80
      # - ./:/var/www/vhosts/myprac/:cached
      # - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      # - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
    depends_on:
      - php
    networks:
      - app-network

  php:
    container_name: myprac_php
    build:
      context: ./docker/dev/php/
    volumes:
      - ./src:/var/www/vhosts/myprac/:cached
      # - ./docker/dev/php/www.conf:/etc/php-fpm.d/www.conf:cached
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: myprac_db
    hostname: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    environment:
      - MYSQL_ROOT_PASSWORD=prac
      - MYSQL_DATABASE=myprac
      - MYSQL_USER=masa
      - MYSQL_PASSWORD=prac
    volumes:
      - ./src/database/config/:/etc/mysql/conf.d/
    platform: linux/x86_64
    networks:
      - app-network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myprac_pma
    hostname: phpmyadmin
    depends_on:
      - db
    ports:
      - "9090:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge